### ISSUE TITLE
Using high-level API of Tensorflow

### ISSUE THREAD

**Issue by quanhua92** [amirziai/ai-with-tensorflow#1]
hi @amirziai ,
There are some high-level APIs such as Estimators and Keras that have been implemented into Tensorflow Core. I suggest that we will use these APIs in this book. There are so many books about low-level Tensorflow API so I think this can be a great improvement. I will use tf.keras in Chapter 4 for CNN first. May be I will introduce the low-level tf.Session approach but then I will introduce tf.keras.applications to use pre-trained model such as Inception net.
You can find the introduction about the high-level API in this video: https://youtu.be/t64ortpgS-E?t=5m49s 
Please tell me what you think.
Thanks.
Quan Hua.

**Comment by amirziai** [comment]
@quanhua92 I think it's a great idea. I will be introducing Keras and Estimators in chapter 2 and 3 so you can assume that the reader has some familiarity.
